# Generated by Django 4.2.7 on 2026-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('discount_percent', models.IntegerField(default=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('rule_type', models.CharField(choices=[('BOGO', 'Buy 1 Get 1 Free'), ('HAPPY_HOUR', 'Happy Hour Discount'), ('CROSS_SELL', 'Cross Sell Bundle')], default='BOGO', max_length=30)),
                ('discount_percent', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
