# Generated by Django 4.2.7 on 2026-07-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=399.0, max_digits=10)),
                ('max_order_amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=1499.0, max_digits=10)),
                ('standard_shipping_charge', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=49.0, max_digits=10)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('guest_checkout_enabled', models.BooleanField(default=True)),
                ('otp_verification_required', models.BooleanField(default=False)),
                ('gift_wrap_charge', models.DecimalField(decimal_places=2, default=49.0, max_digits=10)),
                ('handling_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_searches', models.TextField(default='Lavender, Soy Wax, Scented Pillars, Vanilla Dream, Aromatherapy')),
                ('trending_searches', models.TextField(default='Midnight Jasmine, Rose Garden, Oud Wood')),
                ('synonyms_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='The Candle Lab', max_length=150)),
                ('tagline', models.CharField(default='Artisanal Luxury Candles & Fragrances', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1603006905003-be475563bc59?w=300&q=80')),
                ('dark_logo_url', models.URLField(blank=True, default='')),
                ('favicon_url', models.URLField(blank=True, default='')),
                ('support_email', models.CharField(default='care@thecandlelab.in', max_length=100)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('store_address', models.TextField(default='108 Atelier Avenue, Cyber City, HR 122002')),
                ('social_instagram', models.CharField(default='https://instagram.com/thecandlelab', max_length=200)),
                ('social_facebook', models.CharField(default='https://facebook.com/thecandlelab', max_length=200)),
                ('social_whatsapp', models.CharField(default='+919876543210', max_length=50)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#d97706', max_length=20)),
                ('secondary_color', models.CharField(default='#7c2d12', max_length=20)),
                ('accent_color', models.CharField(default='#fbbf24', max_length=20)),
                ('background_color', models.CharField(default='#0f172a', max_length=20)),
                ('surface_color', models.CharField(default='#1e293b', max_length=20)),
                ('text_primary', models.CharField(default='#f8fafc', max_length=20)),
                ('text_secondary', models.CharField(default='#94a3b8', max_length=20)),
                ('border_radius', models.CharField(default='12px', max_length=20)),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('dark_mode_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
