# Generated by Django 4.2.7 on 2026-07-25 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('icon_symbol', models.CharField(default='🕯️', max_length=20)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('wax_type', models.CharField(choices=[('Soy Wax', 'Soy Wax'), ('Beeswax', 'Beeswax'), ('Coconut Wax', 'Coconut Wax'), ('Paraffin Blend', 'Paraffin Blend')], default='Soy Wax', max_length=50)),
                ('wick_type', models.CharField(choices=[('Wooden Crackling Wick', 'Wooden Crackling Wick'), ('Cotton Wick', 'Cotton Wick')], default='Wooden Crackling Wick', max_length=50)),
                ('burn_time_hours', models.IntegerField(default=50)),
                ('weight_grams', models.IntegerField(default=250)),
                ('top_notes', models.JSONField(default=list)),
                ('middle_notes', models.JSONField(default=list)),
                ('base_notes', models.JSONField(default=list)),
                ('fragrance_strength', models.IntegerField(default=4)),
                ('room_size', models.CharField(default='Medium (Living Room)', max_length=50)),
                ('is_vegan', models.BooleanField(default=True)),
                ('is_handmade', models.BooleanField(default=True)),
                ('is_eco_friendly', models.BooleanField(default=True)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='products', to='products.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('verified_purchase', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
    ]
