# Generated by Django 4.2.7 on 2026-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('waybill_number', models.CharField(max_length=100, unique=True)),
                ('courier_partner', models.CharField(choices=[('Shiprocket', 'Shiprocket Express'), ('Delhivery', 'Delhivery Priority'), ('BlueDart', 'BlueDart Premium'), ('DTDC', 'DTDC Express')], default='Shiprocket', max_length=50)),
                ('current_status', models.CharField(default='Dispatched from Atelier Warehouse', max_length=100)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('sku_capacity', models.IntegerField(default=5000)),
            ],
        ),
    ]
